version: '3.7'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  tic-tac-toe-challenge-be:
    build:
      dockerfile: Dockerfile
      context: './tic-tac-toe-challenge-be'
    depends_on:
      - mongodb
    volumes:
      - /app/node_modules
      - ./tic-tac-toe-challenge-be:/app
    ports:
      - 5000:5000
    links: [mongodb]
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/tic-tac-toe  
      - WAIT_HOSTS=mongodb:27017
      - WAIT_TIMEOUT= 60

  tic-tac-toe-challenge:
    depends_on:
      - tic-tac-toe-challenge-be
    build:
      context: ./tic-tac-toe-challenge
    environment:
      - CHALLENGE_BACKEND:http://localhost:5000/api/v1/play
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./tic-tac-toe-challenge:/app

volumes:
  mongodata:
